global:
  scrape_interval: 15s
scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
    metric_relabel_configs:
      # keep only this stack's containers
      - source_labels: [container_label_com_docker_compose_project]
        regex: cipp-local
        action: keep
